carpoolApplication/config/routes.rb
Rails.application.routes.draw do

  resources :rides
  resources :cars
  resources :drivers
  root 'application#hello'

  resources :users
  resources :rider_applications
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

carpoolApplication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%=stylesheet_link_tag "application.css"%>

  <header>
      <div>
        <ul class="navbar">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Rides", rider_applications_path%></li>
          <% if current_user %>
          <li><%= link_to "Driver Page", drivers_path%></li>
          <% end %>
          <% if admin? %>
            <li><%= link_to "Cars", cars_path%></li>
            <li> <%=link_to "Users", users_path%></li>
          <% end %>
          <% if current_user %>
            <li style="float:right"><%= link_to current_user.first_name + " " + current_user.last_name, logout_path %></li>
          <% else %>
            <li style="float:right"><%= link_to "Log In", login_path %></li>
          <% end %>
        </ul>
      </div>
  </header>

  <body>
      <div class='content'>
          <!--devise gem configuration-->
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
      </div>
  </body>
</html>