carpoolApplication/config/routes.rb
Rails.application.routes.draw do

  resources :rides
  resources :cars
  resources :drivers
  root 'application#hello'

  resources :users
  resources :rider_applications
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

carpoolApplication/app/models/rider_application.rb
class RiderApplication < ApplicationRecord
  validates_format_of   :Name,              presence: true, :with => /[a-z]/
  validates_format_of   :city,              presence: true, :with => /[a-z]/
  validates             :Phone,             presence: true, :numericality => {:only_integer => true,  length: { is: 10} }
  validates             :zip_code,          presence: true, :numericality => {:only_integer => true,  length: { is: 5}  }
  validates             :number_passengers, presence: true, :numericality => {:only_integer => true}
  validates_inclusion_of :zip_code, :in => [77840, 77845, 77801, 77802, 77803]
  validates_inclusion_of :city, :in => ["College Station", "Bryan", "college station", "bryan"]

  STATUS =%w[pending in_progress finished].freeze
end

carpoolApplication/app/controllers/rider_applications_controller.rb
class RiderApplicationsController < ApplicationController
  before_action :set_rider_application, only: [:show, :edit, :update, :destroy]

  # GET /rider_applications
  # GET /rider_applications.json
  def index
    @rider_applications = RiderApplication.order(ride_status: :desc)
  end

  # GET /rider_applications/1
  # GET /rider_applications/1.json
  def show
  end

  # GET /rider_applications/new
  def new
    @rider_application = RiderApplication.new
  end

  # GET /rider_applications/1/edit
  def edit
  end

  # POST /rider_applications
  # POST /rider_applications.json
  def create
    @rider_application = RiderApplication.new(rider_application_params)
    respond_to do |format|
      if @rider_application.save
        format.html { redirect_to @rider_application, notice: 'Rider application was successfully created.' }
        format.json { render :show, status: :created, location: @rider_application }
      else
        format.html { render :new }
        format.json { render json: @rider_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rider_applications/1
  # PATCH/PUT /rider_applications/1.json
  def update
    respond_to do |format|
      if @rider_application.update(rider_application_params)
        format.html { redirect_to @rider_application, notice: 'Rider application was successfully updated.' }
        format.json { render :show, status: :ok, location: @rider_application }
      else
        format.html { render :edit }
        format.json { render json: @rider_application.errors, status: :unprocessable_entity }
      end
    end
    @rider_application.ride_status = update_status
  end

  def update_status
    if @rider_application.driver_name.nil?
      @rider_application.ride_status = "pending"
    else
      @rider_application.ride_status = "in_progress"
    end
  end

  # DELETE /rider_applications/1
  # DELETE /rider_applications/1.json
  def destroy
    @rider_application = RiderApplication.find(params[:id])
    @rider_application.destroy
    respond_to do |format|
      format.html { redirect_to rider_applications_url, notice: 'Rider application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rider_application
      @rider_application = RiderApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rider_application_params
      params.require(:rider_application).permit(:Name, :Phone, :street_address, :zip_code, :city, :number_passengers, :ride_status, :driver_name, :application_received)
    end
end

carpoolApplication/app/views/rider_applications/_form.html.erb
<%= form_for(rider_application) do |f| %>
  <% if rider_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rider_application.errors.count, "error") %> prohibited this rider_application from being saved:</h2>

      <ul>
      <% rider_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :Name %>
  </div>

  <div class="field">
    <%= f.label :Phone %>
    <%= f.text_field :Phone , maxlength: 10%>
  </div>

  <div class="field">
    <%= f.label :street_address %>
    <%= f.text_field :street_address %>
  </div>

  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code , maxlength: 5 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :number_passengers %>
    <%= f.text_field :number_passengers %>
  </div>

  <div class="field">
    <%= f.label :ride_status %>
    <%= f.collection_select :ride_status, RiderApplication::STATUS, :strip, :humanize %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes, :cols => "40", :rows => "5" %>
  </div>

  <div class="field">
    <%= f.label :driver_name %>
    <%= f.text_field :driver_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

carpoolApplication/app/views/rider_applications/edit.html.erb
<h1>Editing Rider Application</h1>

<%= render 'form', rider_application: @rider_application %>


<%= link_to 'Show', @rider_application %> |
<%= link_to 'Back', rider_applications_path %>

carpoolApplication/app/views/rider_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pending Rides</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Street Address</th>
      <th>Zip Code</th>
      <th>City</th>
      <th>Number of Passengers</th>
      <th>Notes</th>
      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @rider_applications.each do |rider_application| %>
      <tr <% if rider_application.ride_status == "in_progress" %> style="background-color: yellow" <%end %>
          <% if rider_application.ride_status == "finished" %> style="background-color: mediumspringgreen" <%end %> >
        <% if rider_application.ride_status == "pending" %>
        <td><%= rider_application.Name %></td>
        <td><%= rider_application.Phone %></td>
        <td><%= link_to rider_application.street_address, "https://www.google.com/maps/search/?api=1&query=" + rider_application.street_address + " " + rider_application.city%></td>
        <td><%= rider_application.zip_code %></td>
        <td><%= rider_application.city %></td>
        <td><%= rider_application.number_passengers %></td>
          <%  if can? :update, @rider_application %>
            <td><%= link_to "Ride Notes",  edit_rider_application_path(rider_application)%></td>
          <% else %>
            <td><%= rider_application.notes %></td>
          <% end %>
        <td><%= button_to 'Show', rider_application %></td>
<!--          <td> <%#= link_to 'Ride Groupings', rides_path%></td>-->
        <td><%= button_to 'Delete', rider_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Rides In Progress</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Street Address</th>
      <th>Zip Code</th>
      <th>City</th>
      <th>Number of Passengers</th>
      <th>Notes</th>
      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @rider_applications.each do |rider_application| %>
      <tr <% if rider_application.ride_status == "in_progress" %> style="background-color: yellow" <%end %>
          <% if rider_application.ride_status == "finished" %> style="background-color: mediumspringgreen" <%end %> >
        <% if rider_application.ride_status == "in_progress" %>
        <td><%= rider_application.Name %></td>
        <td><%= rider_application.Phone %></td>
        <td><%= link_to rider_application.street_address, "https://www.google.com/maps/search/?api=1409+w+brookside+dr" %></td>
        <td><%= rider_application.zip_code %></td>
        <td><%= rider_application.city %></td>
        <td><%= rider_application.number_passengers %></td>
          <%  if can? :update, @rider_application %>
            <td><%= link_to "Ride Notes",  edit_rider_application_path(rider_application)%></td>
          <% else %>
            <td><%= rider_application.notes %></td>
          <% end %>
        <td><%= button_to 'Show', rider_application %></td>
        <td><%= button_to 'Destroy', rider_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Completed Rides</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Street Address</th>
      <th>Zip Code</th>
      <th>City</th>
      <th>Number of Passengers</th>
      <th>Notes</th>
      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @rider_applications.each do |rider_application| %>
      <tr <% if rider_application.ride_status == "in_progress" %> style="background-color: yellow" <%end %>
          <% if rider_application.ride_status == "finished" %> style="background-color: mediumspringgreen" <%end %> >
        <% if rider_application.ride_status == "finished" %>
        <td><%= rider_application.Name %></td>
        <td><%= rider_application.Phone %></td>
        <td><%= link_to rider_application.street_address, "https://www.google.com/maps/search/?api=1409+w+brookside+dr" %></td>
        <td><%= rider_application.zip_code %></td>
        <td><%= rider_application.city %></td>
        <td><%= rider_application.number_passengers %></td>
          <%  if can? :update, @rider_application %>
            <td><%= link_to "Ride Notes",  edit_rider_application_path(rider_application)%></td>
          <% else %>
            <td><%= rider_application.notes %></td>
          <% end %>
        <td><%= button_to 'Show', rider_application %></td>
        <td><%= button_to 'Destroy', rider_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rider Application', new_rider_application_path %>

carpoolApplication/app/views/rider_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rider_application.Name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @rider_application.Phone %>
</p>
<p>
  <strong>Street Address:</strong>
  <%= @rider_application.street_address %>
</p>
<p>
  <strong>Zip Code:</strong>
  <%= @rider_application.zip_code %>
</p>
<p>
  <strong>City:</strong>
  <%= @rider_application.city %>
</p>
<p>
  <strong>Number of Passengers:</strong>
  <%= @rider_application.number_passengers %>
</p>

<p>
  <strong>Ride Status:</strong>
  <%= @rider_application.ride_status %>
</p>

<p>
  <strong>Driver Name:</strong>
  <%= @rider_application.driver_name %>
</p>

<% if @rider_application.ride_status == "in_progress" %>
  <%= link_to 'Show Ride Groupings', rides_path %>
<% end %>
<br>

<%= link_to 'Edit', edit_rider_application_path(@rider_application) %> |
<%= link_to 'Back', rider_applications_path %> 